# Generated by Django 5.2.3 on 2025-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_report_ai_generated_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="originality_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
