# Generated by Django 5.2.3 on 2025-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_report_originality_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports_files/'),
        ),
    ]
